"""Add CDA tables fresh

Revision ID: 6ded1ebd709c
Revises: 910bc7f3e15f
Create Date: 2026-04-29 15:03:19.940477

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ded1ebd709c'
down_revision: Union[str, Sequence[str], None] = '910bc7f3e15f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('query_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=128), nullable=True),
    sa.Column('query_text', sa.Text(), nullable=False),
    sa.Column('response_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_query_cache_id'), 'query_cache', ['id'], unique=False)
    op.create_index(op.f('ix_query_cache_session_id'), 'query_cache', ['session_id'], unique=False)
    op.create_table('session_context',
    sa.Column('session_id', sa.String(length=128), nullable=False),
    sa.Column('current_topic', sa.String(length=255), nullable=True),
    sa.Column('tables_used', sa.JSON(), nullable=True),
    sa.Column('columns_used', sa.JSON(), nullable=True),
    sa.Column('filters_used', sa.JSON(), nullable=True),
    sa.Column('intent_type', sa.String(length=64), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('session_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('session_context')
    op.drop_index(op.f('ix_query_cache_session_id'), table_name='query_cache')
    op.drop_index(op.f('ix_query_cache_id'), table_name='query_cache')
    op.drop_table('query_cache')
    # ### end Alembic commands ###
